### ISSUE TITLE
모임통장 이벤트참여_빅매치

### ISSUE THREAD

**Issue by egon6018** [TogetherHana/Frontend#15]
## 📌 Feature Issue

모임통장 이벤트 참여_빅매치

## 📝 To-do

- [x] 투표마감시간 전 투표하지 않은 사람 화면
- [x] 투표마감시간 전 이미 투표한 사람 화면 -> 수정못하도록 구현 (라디오버튼과 '한배타기'버튼 안보이게)
- [x] 투표마감시간 후 화면 -> 총무가 승리호 결정 
- [x] 빅매치이벤트 결과 화면  -> 승리호가 아닌 나머지 배들을 선택한 모든 유저들은 loser가 됨
- [x] 빅매치 생성화면
