### ISSUE TITLE
플랫폼 메인화면

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#18]
## 📌 Feature Issue

함께, 하나? 플랫폼의 메인화면을 구성합니다

## 📝 To-do

- [x] 응원팀 설정 전 메인화면
- [x] 응원팀 설정 후 메인화면
- [x] 모임통장 초대 → 초대링크 화면
- [x] 화면 비율에 따라 위치 변경되도록 반응형 설정
