### ISSUE TITLE
빅매치 투표 API연결

### ISSUE THREAD

**Issue by egon6018** [TogetherHana/Frontend#27]
## 📌 Feature Issue

빅매치 투표 API연결

## 📝 To-do

- [x] 투표 후, 한배타기 버튼을 클릭했을 때, 호출하는 API 연결하기
- [x] 총무가 승리호 결정 누를 때 요청하는 API 연결하기 
- [x] 투표마감 후, 승리한 선택지를 고르고 승패를 가르기
- [x] 투표 마감 여부에 따라 두 화면으로 나뉘는데, 투표 마감 전일 경우 전자의 페이지로, 투표 마감 후일 경우 후자의 페이지로 이동하도록 API연결하기
