### ISSUE TITLE
상태 관리 시작

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#31]
## 📌 Feature Issue

상태관리를 위한 작업을 시작합니다

## 📝 To-do

- [x] 모임통장 회원가입 화면간 연결
- [x] 화면 연결 간에 react-query를 활용해 상태 관리 진행
- [ ] storybook을 활용한 컴포넌트 재정립
