### ISSUE TITLE
모임통장 회비걷기 & 돈보내기 & MY응원팀설정

### ISSUE THREAD

**Issue by egon6018** [TogetherHana/Frontend#34]
## 📌 Feature Issue

모임통장 회비걷기 & 돈보내기

## 📝 To-do

- [x] 모임통장 회비걷기 api연결
- [x] 모임통장 회비걷기 화면 반응형으로 리팩토링
- [x] 모임통장 돈 어디로 보낼지 은행선택 화면구현
- [x] 모임통장 돈 보내기 화면구현
- [x] 모임통장 돈보내기 api연결
- [x] 응원팀설정 화면 반응형으로 리팩토링
- [x] 응원팀설정 api연결
