### ISSUE TITLE
회원가입 API 연결

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#35]
## 📌 Feature Issue

플랫폼 회원가입 API 연결을 진행합니다

## 📝 To-do

- [x] 디바이스 토큰이 없을 경우 회원가입 화면 진입
- [x] 디바이스 토큰이 있을 경우 회원가입 화면 대신 메인 홈 화면으로 진입
- [x] 알림허용 화면 추가
- [x] 본인인증
  - [x] 전화번호 인증
  - [x] 계좌 연동
  - [x] 거래 내역 확인 후 1원인증
  - [x] 닉네임 설정
  - [ ] 가입 완료 후 가입 정보 BE 전송
