### ISSUE TITLE
모임통장생성 API연결

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#41]
## 📌 Feature Issue

모임통장생성 FE-BE API 연결 작업을 진행합니다

## 📝 To-do

- [x] 주민등록증 OCR? -> 추후 논의해보기
- [x] 모임통장 약관 동의 여부
- [x] 모임통장 정보 수집 후 최종 생성 절차
