### ISSUE TITLE
홈화면 정보 API 연동

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#42]
## 📌 Feature Issue

홈화면에 필요한 정보를 가져오는 API 연동 작업입니다

## 📝 To-do

- [x] deviceToken을 통해 홈화면 진입 후 해당 사용자 정보 가져오기
  - [x] 사용자 이름 출력 -> 닉네임 출력
  - [x] 속해있는 모임통장 리스트 출력
  - [x] 사용자 마일리지 출력
