### ISSUE TITLE
모임통장 초대코드 발급 및 참여 API 연동

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#45]
## 📌 Feature Issue

기존 모임통장 초대코드 발급 및 참여 FE-BE 연동
오류사항 수정

## 📝 To-do

- [x] 기존 모임통장 초대코드 발급
- [x] 발급된 초대코드로 모임통장 가입
- [x] 완료
- [x] 오류사항
  - [x] 회원가입후 메인화면 이동 안됨
  - [x] 회원가입할때 닉네임 db 반영 안됨
  - [x] 초대하기 모달 배경 검은색 해결
  - [x] /memberhome 새로고침 하면 에러 뜸 → 이거는 약간의 로딩?이 필요할듯 data hmm.. -> 나중에
  - [x] 스포츠마일리지 무료 마일리지 받기 margin → absolute
