### ISSUE TITLE
토큰 연결 및 전체적으로 부족한 부분 수정

### ISSUE THREAD

**Issue by egon6018** [TogetherHana/Frontend#47]
## 📌 Feature Issue

토큰 연결 및 전체적으로 부족한 부분 수정

## 📝 To-do

- [x] api 연동완료한 모든 화면에 토큰을 연결하여 잘 작동하는지 다시 확인
- [x] 기타 자잘한 것들 수정 (리팩토링)
- [x] 친구리스트에서 '추가'버튼 누르면 친구추가 url보내기(?)
