### ISSUE TITLE
기능들 몇개 수정

### ISSUE THREAD

**Issue by egon6018** [TogetherHana/Frontend#57]
## 📌 Feature Issue

총무만 회비걷기 및 보내기 할 수 있게 수정하기
빅매치이벤트에서 이미 투표한 사람 라디오버튼 check표시나게 gameOptionIdx값 받아오기

## 📝 To-do

- [x] 총무만 회비걷기 및 보내기 할 수 있게 수정하기
- [ ] 빅매치이벤트에서 이미 투표한 사람 라디오버튼 check표시나게 gameOptionIdx값 받아오기
- [x] 화면들 반응형으로 리팩토링
- [ ] 모임통장 홈화면 (/baseball/home) 반응형 한번 더 수정봐야 함
