### ISSUE TITLE
모임통장 가입

### ISSUE THREAD

**Issue by tkdalsss** [TogetherHana/Frontend#7]
## 📌 Feature Issue

모임통장 가입하는 화면을 구성합니다

## 📝 To-do

- [x] 상품 소개
- [x] 준비물 안내
- [x] 본인정보 확인
- [x] 종목 선택
- [x] 약관 동의
- [x] 약관 동의 확인
- [x] 계좌 이름 설정
- [x] 계좌 비밀번호 설정
- [x] 계좌 비밀번호 설정 확인
- [x] 계좌 생성정보 확인
- [x] 계좌 생성정보 확인 후 생성
- [x] 계좌 생성 완료
